import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClientProviders } from "@/components/provider/client-provider";
import ModalProvider from "@/components/provider/modal-provider";

const font = Poppins({ weight:['200','400','700','900'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
      <ClientProviders>  
            {children} 
            <ModalProvider/>
        </ClientProviders>
     
        </body>
    </html>
  );
}
